variables:
  PLUGIN_NAME: 'userInterfaceTermReplacement'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'