variables:
  PLUGIN_NAME: 'userInterfaceTermReplacement'

include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ops/cypress_tests.yml'

.integration_tests_template:
  before_script:
    - patch /var/www/$CY_APPLICATION/lib/pkp/classes/i18n/Locale.php < cypress/fixtures/Fix_hook_translation.patch
